// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJL3IPojWOKdMGuqWpLoMc3pGF-CYGeOs',
    appId: '1:402537311878:web:5dc4a9d8ecc4846aeaeb07',
    messagingSenderId: '402537311878',
    projectId: 'seerahtimeline-18021',
    authDomain: 'seerahtimeline-18021.firebaseapp.com',
    storageBucket: 'seerahtimeline-18021.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRDxOuqCiI6AsHZdSypamJ0Yj5sPaWVt8',
    appId: '1:402537311878:android:95c446312c7bcd2ceaeb07',
    messagingSenderId: '402537311878',
    projectId: 'seerahtimeline-18021',
    storageBucket: 'seerahtimeline-18021.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGH7MA6gAIdrZZpZaN4X5dfBpgYOEP7Kw',
    appId: '1:402537311878:ios:397ced5563727f88eaeb07',
    messagingSenderId: '402537311878',
    projectId: 'seerahtimeline-18021',
    storageBucket: 'seerahtimeline-18021.firebasestorage.app',
    iosBundleId: 'com.example.seerahTimeline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGH7MA6gAIdrZZpZaN4X5dfBpgYOEP7Kw',
    appId: '1:402537311878:ios:397ced5563727f88eaeb07',
    messagingSenderId: '402537311878',
    projectId: 'seerahtimeline-18021',
    storageBucket: 'seerahtimeline-18021.firebasestorage.app',
    iosBundleId: 'com.example.seerahTimeline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJL3IPojWOKdMGuqWpLoMc3pGF-CYGeOs',
    appId: '1:402537311878:web:512812237847a066eaeb07',
    messagingSenderId: '402537311878',
    projectId: 'seerahtimeline-18021',
    authDomain: 'seerahtimeline-18021.firebaseapp.com',
    storageBucket: 'seerahtimeline-18021.firebasestorage.app',
  );
}
